### ISSUE TITLE
Make steal.js a dependency?

### ISSUE THREAD

**Issue by blink1073** [phosphorjs/phosphor-plugins#3]

**Comment by sccolbert** [comment]
Good question. At some point, one needs to add a script tag. The question is where should that tag point? If we want to fully hide steal, we shouldn't let that abstraction leak.

**Comment by blink1073** [comment]
Steal isn't just one file either, there is an `ext` folder.  We could bundle it in this repo and point to a https://rawgit.com/ CDN.

**Comment by blink1073** [comment]
Actually, we'd need a different CDN provider: https://rawgit.com/faq#rawgit-com-in-production

**Comment by blink1073** [comment]
Paging @rgbkrk, thoughts?

**Comment by sccolbert** [comment]
No longer relevant in lieu of ba12f1733e3b479e8a0fec6690b8444e7382c319

**Comment by rgbkrk** [comment]
We definitely have the ability to run our own CDN endpoint, though I can't tell if that's moot now.

**Comment by sccolbert** [comment]
The decision of whether it's needed for *this* repo is moot. It may not be moot for the end users application (like the notebook), which may want to use StealJS in order to auto-configure the system importer. This repo no longer relies on StealJS, however.
